### ISSUE TITLE
Could we have some sample code for running?

### ISSUE THREAD

**Issue by whitneypanye** [fweidner/UE4-Plugin-OffAxis#10]
Could you please give us more detail - how to actually running this code, if we don't have optitrack. For example, if we only have a kinect etc. How could we run it via blueprint?

**Comment by LanslotChung** [comment]
This demo work successfully,but i put plugin to my new project, drag OffAxisActor to scene ,set position to (0,0,0),set ExtentPoint to (9,-500,-500),and VirtualScreen Scale（10,10,0）,now click play,it not work.why?Do i forget some settings?

my English is not good,hope you can understand.

**Comment by fweidner** [comment]
Did you change the GameViewPortClient in your settings?
"Project Settings > Engine - General Settings > Game Viewport Client Class" should be OffAxisGameViewportClient

**Comment by LanslotChung** [comment]
![sp180815_150716](https://user-images.githubusercontent.com/27679705/44135708-d65134e0-a09c-11e8-89b1-43b114f5bc76.png)
![sp180815_150608](https://user-images.githubusercontent.com/27679705/44135710-dcc94d30-a09c-11e8-9d03-3aa76174ee94.png)
![sp180815_150622](https://user-images.githubusercontent.com/27679705/44135753-00e36fe8-a09d-11e8-80b2-edf0e44e7789.png)

it seems wrong.

**Comment by LanslotChung** [comment]
Ok ,i got it,i forget to set NearClippingPlane,Demo is set to .1f,but my new project is 10.

**Comment by fweidner** [comment]
Great! I'll add this to the instructions!
