### ISSUE TITLE
Unable to build in 4.19 and 4.20

### ISSUE THREAD

**Issue by masterofshapes** [fweidner/UE4-Plugin-OffAxis#11]
![image](https://user-images.githubusercontent.com/4534991/43330599-83889682-9178-11e8-989c-26be3cefc066.png)

Got these errors when trying to build in 4.20 should I sub ViewRect for "CameraConstrainedViewRect" ?

**Comment by masterofshapes** [comment]
So I managed to get it to build by changing the 'ViewRect' to 
View->UnconstrainedViewRect.Width(), View->UnconstrainedViewRect.Width()

however now that ive gotten the plugin enabled and have fixed disabled optitrack input I get an immediate crash when i press play. 

![image](https://user-images.githubusercontent.com/4534991/43370416-88cb8b74-9333-11e8-96df-b034f5f002ad.png)


This are errors debug throws on crash

**Comment by DaveTovell** [comment]
You need to add #include "CoreMinimal.h" to OffAxisViewportClient.h
This has stopped it crashing. But so far it just looks like the camera rotates in the scene rather than distorting the view. Will keep playing.

**Comment by whitneypanye** [comment]
I am try to ungrade this to 4.19. Has the same issue..

**Comment by fweidner** [comment]
Just pushed an update to for building with 4.19.

**Comment by whitneypanye** [comment]
I've try 4.19, but once I load the code download from master, the screen is not showing anything?

**Comment by fweidner** [comment]
I experience the same issue after a rebuild. Right now, I don't have an immediate fix.
If anyone has time to investigate thee issue, let us know.

**Comment by fweidner** [comment]
Just a heads-up: I updated the plugin to 4.20. It compiles but the lighting is still off. I'm working on it.

**Comment by fweidner** [comment]
Another one: The plugin works for 4.20 (version 2.0.1)

**Comment by masterofshapes** [comment]
Thanks any instructions on how to use, say we wanted to use in my case was planning on using vive tracker to give position data

**Comment by fweidner** [comment]
There's now an updated version of the Readme and an example project for 4.20 :)
