### ISSUE TITLE
GPLv3 incompatible with UE4

### ISSUE THREAD

**Issue by muchcharles** [fweidner/UE4-Plugin-OffAxis#16]
The GPLv3 license this is under is incompatible with UE4; you could never distribute this combined with a UE4 project, even non-commercially.

I think lgpl is the closest you can get, which would require source changes to the plugin be provided, but wouldn't require the engine and applications to make their source available under the same terms.

( https://answers.unrealengine.com/questions/777669/plugins-using-lgpl-libs-allowed-in-unreal-marketpl.html <-- they clarify there lgpl is allowed with projects that are made with the engine, but not on the marketplace (only MIT, BSD, etc. there), but GPLv2/3 is allowed with neither ).

**Comment by fweidner** [comment]
Thank you! I wasn't aware of this issue (shame on me!) 
MIT should work, right?

**Comment by muchcharles** [comment]
Yeah, I think I've seen several plugins using MIT.
