### ISSUE TITLE
"NotImplementedYet" Error (SteamVR)

### ISSUE THREAD

**Issue by GregFinger** [fweidner/UE4-Plugin-OffAxis#20]
using version v2.1.1 and the UE4Project / OffAxisTest. Unreal 4.2.2

When i select SteamVR as my Tracking Device and play the scene, my window fills up with the error NotImplementedYet. Any idea what's going on here?

**Comment by fweidner** [comment]
Sorry! Currently, there is no support SteamVR tracking (simply because I did not need it yet). It's in the blueprint because someone asked me where he should apply the tracking data from SteamVR/Lighthouse. So, it's just there so it's known where to update the eye position with tracking from the lighthouse system. 

Sorry for the confusion.

**Comment by GregFinger** [comment]
Ok, coming back to this. So what you're saying is if I input the Vive Tracker xyz positional data in the Do_Steam_VR blueprint's Relative Eye Position, and on the OffAxisActor set the Tracking Device parameter to SteamVR, then that's all i need to get the system working?

**Comment by fweidner** [comment]
In theory, yes :)
There might by some wrangling of the coordinates necessary. The OffAxisPlugin uses the following coordinate [system:](https://github.com/fweidner/UE4-Plugin-OffAxis/blob/master/CoordinateSystemOffAxis.png).

Here is how I've done it in for Optitrack (it's in the [OffAxisActor_CustomOptitrack.uasset](https://github.com/fweidner/UE4-Plugin-OffAxis/blob/master/Content/OffAxisActor_CustomOptitrack.uasset!

[1](https://user-images.githubusercontent.com/16336130/57756555-cd990980-76f3-11e9-88bb-d29f8d17445c.PNG)
![2](https://user-images.githubusercontent.com/16336130/57756556-cd990980-76f3-11e9-9f58-b5c46abb7490.PNG)

**Comment by GregFinger** [comment]
I have my Vive attached to another computer that sends values over OSC to the computer running the unreal project. Glad to say it's working without issue using this workflow:

<img width="1292" alt="Screen Shot 2019-05-30 at 2 17 50 AM" src="https://user-images.githubusercontent.com/10980617/58581214-92fda800-8281-11e9-9143-2b00fe04d868.png">

**Comment by fweidner** [comment]
Glad to hear that!
