### ISSUE TITLE
All Nodes Have Errors

### ISSUE THREAD

**Issue by jessekirbs** [fweidner/UE4-Plugin-OffAxis#23]
I'm using Unreal 4.23 with the latest version of this plug-in. I start a new Unreal C++ project, copy the OffAxis files into the Plugins folder, open the project, and activate the plugin. The OffAxisActorManual has many errors - all of them having to do with the Off Axis custom nodes. I've attached a picture of an example. This error is on all Off Axis nodes. 

![offaxis](https://user-images.githubusercontent.com/8700046/71462965-cd70ea00-2769-11ea-8fb9-f85fa65597ab.PNG)

![error](https://user-images.githubusercontent.com/8700046/71491187-05b50e80-27e4-11ea-992b-8ad16e8ea7cc.PNG)

EDIT: I just realized that OffAxisPlayer is not an option when trying to change the LocalPlayer. I tried creating a project with 4.21, added your plugin, and now saw this as an option. In 4.23 it was not listed. I imagine my errors are stemming from this.

I've managed to get this working in 4.22 I believe. It's hard to tell if it's working correctly because I'm not 100% sure of the setup requirements. Do you have an example map so I can make sure mine is setup correctly? Are we supposed to place any other cameras/pawns in the level or just place the OffAxisActor at 0,0,0 and hit play? 

Any help would be greatly appreciated. Thank you!

**Comment by fweidner** [comment]
Hi,

yes, you have to use the OffAxisLocalPlayer for now. I'm planning to remove this dependency (but it's not happening soon 😄)

Also, here's a version that should work out of the box: https://github.com/fweidner/UE4-Plugin-OffAxis/releases/download/v2.0.1/OffAxisProjection.zip

Placing the OffAxisActor at 0,0,0 should do the trick for testing. The OffAxisActors has three cubes as child components that you can use to adjust the size of the display. You can also move and rotate the OffAxisActor but not all degrees of freedom are possible atm (see #14) 

Best, 
Florian

**Comment by jessekirbs** [comment]
Florian,

Thanks for the reply and for the plugin link. I was wondering if you had an
example project in Unreal (like the one you have setup in the example .gif
on Github) that I could take a look at to see a complete working example. I
want to make sure I'm setting things up correctly because it looks a bit
weird on my end. I appreciate you taking the time to help me out!

Jesse

**Comment by fweidner** [comment]
Hi Jesse,

Sorry, I put the wrong link in my answer 😄 here's the correct one: 
https://github.com/fweidner/UE4-Plugin-OffAxis/releases/download/v2.1.2/Demo.zip
Here you can find a zip archive called Demo.zip that contains a working example.
 (I also corrected the link in the original answer.)

Best, 
Florian

**Comment by jessekirbs** [comment]
Florian - Thank you so much! The demo looks great and I know for sure my
setup is incorrect after seeing that. Would you mind providing me the
Unreal project for that Demo so I can see the setup within Unreal?

Jesse

**Comment by fweidner** [comment]
Hi,

I'm sending you a link today or tomorrow 👍 Can I reach you via eMail (or discord)? 

Also, could you check that you followed the steps mentioned in the project description here on github:
Assuming you start with a Basic Code C++ project:
* Update LocalPlayer class in Edit->Project Settings->General Settings
* Adjust Input mappings to your Config/DefaultInput.ini
* Drag the OffAxisActor in your scene
* Set position of OffAxisActor to 0,0,0
* In the OffAxisActor, place the child actors P_a, P_b, and P_c so that the correspond to the corners of your "virtual window".
* Change your NearClippingPlane .1f

It is just so that I can determine how to improve the setup description and allow others an smoother start when using the plugin 😄 If you find the issue in your setup, I would really appreciate it if you could keep me posted so that I can update the readme/howto.

Best, 
Florian

**Comment by jessekirbs** [comment]
Thanks again. I really appreciate it! I will check all those steps again
tomorrow morning and let you know. Take care.

Jesse

**Comment by jessekirbs** [comment]
Hey Florian - Sorry for the delay. I checked my project and I made sure I
followed all of the steps you outlined. A couple things:

Do I adjust the StartPositionEye object at all?
Do I change the Near Clip Plane in the project settings? If so, I did do
that but I don't see where the 'f' comes in as in .1f. It doesn't let me
type that.

If I could get the download link for the setup project that would be very
helpful so I could reverse engineer and see what's wrong with mine and let
you know. Thanks, Florian!

Jesse

**Comment by jessekirbs** [comment]
Florian - just wanted to check it again and see if you're able to send me
that project download link. Eager to check it out. Thanks so much!

Jesse

**Comment by fweidner** [comment]
> Do I change the Near Clip Plane in the project settings? If so, I did do
> that but I don't see where the 'f' comes in as in .1f. It doesn't let me
> type that

Yes, you need to change that. Just enter ".1".

**Comment by fweidner** [comment]
I just prepared an non-production ready example project. Can I reach you via email or Discord so I can get it to you?

**Comment by jessekirbs** [comment]
Thank you so much! Email at jessekirbs @gmail.com is perfect. Much
appreciated!

**Comment by fweidner** [comment]
Thx. I've send you a link to a project. I also removed your eMail from the comment above.
