### ISSUE TITLE
How to using this for own new project

### ISSUE THREAD

**Issue by fingerx** [fweidner/UE4-Plugin-OffAxis#7]
hello,  i am new in ue .thanks for share this plugins. can you tell me how to use new ue project,thanks

**Comment by fweidner** [comment]
Hi! 

I'll try to prepare an example project today. 

1. Basically, you add the plugin to your project. 
2. In your project settings, you need to change the GameViewportClient to OffAxisGameViewportclient. 
3. Then, in your level, you add the OffAxisActor from the plugin. 
4. You can specify height and width of the virtual window with the cube in the OffAxisActor. 
5. Your player should start at (0,0,0).

There are some InputActions in the OffAxisActor. With them you can control movement. Note that your character movement does not work anymore. Every movement is done via the EyeOffset in the OffAxisActor. Rotation is ignored. 

I hope this gets you started. I'll try to make this more detailed soon! If you have any questions feel free to ask!

Best, 
Florian

**Comment by fingerx** [comment]
@fweidner ,thanks very much but i cant build your github source code using Unreal 4.21. Build many time but failed. I searech [https://answers.unrealengine.com/questions/399214/how-to-manually-build-plugins.html](url) link and follow this but alway error.

**Comment by fingerx** [comment]
@fweidner  compile is ok but offaix actor bp many error.  i thank offaix plugins load failed. need your help.thanks

**Comment by fingerx** [comment]
@fweidner  sorry ,this my setting error, copy Resources Folder  load offaix plugins is ok.thanks
