### ISSUE TITLE
Why use ViewClient not LocalClient?

### ISSUE THREAD

**Issue by DantaliaN00** [fweidner/UE4-Plugin-OffAxis#9]
Not really an issue, but...

Why you use a ViewClient subclass and override whole Draw function with copy-paste it from a parent when you can override LocalPlayer->CalcSceneView and just check "if (view)" in it?

**Comment by fweidner** [comment]
Thx @DantaliaN00!
Moved from ViewClient to LocalClient in https://github.com/fweidner/UE4-Plugin-OffAxis/commit/954198ed3ecbfd596879f7a5a3a7ce4b5847d9a8
